// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhULYJ0cTN7qbSjV7t2H6v-EXb0MzKVeM',
    appId: '1:952005346716:web:c59869e2fdd4aad380f459',
    messagingSenderId: '952005346716',
    projectId: 'fir-auth-80ba3',
    authDomain: 'fir-auth-80ba3.firebaseapp.com',
    storageBucket: 'fir-auth-80ba3.appspot.com',
    measurementId: 'G-0MH22F6RLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgfekVgNUh90vYMWG3R6ZbLdN2Pho8EBc',
    appId: '1:952005346716:android:c6c3064b61324a3a80f459',
    messagingSenderId: '952005346716',
    projectId: 'fir-auth-80ba3',
    storageBucket: 'fir-auth-80ba3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQHX9Y7-LHhvyKNSTB2JqRCEPzPviXmOk',
    appId: '1:952005346716:ios:9c6fe59de314f94a80f459',
    messagingSenderId: '952005346716',
    projectId: 'fir-auth-80ba3',
    storageBucket: 'fir-auth-80ba3.appspot.com',
    iosClientId: '952005346716-tepruiv7k5v62otjl61t9i2f6v7lmk87.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQHX9Y7-LHhvyKNSTB2JqRCEPzPviXmOk',
    appId: '1:952005346716:ios:9c6fe59de314f94a80f459',
    messagingSenderId: '952005346716',
    projectId: 'fir-auth-80ba3',
    storageBucket: 'fir-auth-80ba3.appspot.com',
    iosClientId: '952005346716-tepruiv7k5v62otjl61t9i2f6v7lmk87.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailAuth',
  );
}
