// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPofb6zc30efTB404LxchZa1iH4S5GYSg',
    appId: '1:1092688138672:web:062314ec2a1386f0764675',
    messagingSenderId: '1092688138672',
    projectId: 'fir-flutter-test-f5430',
    authDomain: 'fir-flutter-test-f5430.firebaseapp.com',
    storageBucket: 'fir-flutter-test-f5430.appspot.com',
    measurementId: 'G-P8BKY9HNW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPptPjDzvj4oxvZqFxCc2INVCpSIg6IHc',
    appId: '1:1092688138672:android:38cdef99f55af900764675',
    messagingSenderId: '1092688138672',
    projectId: 'fir-flutter-test-f5430',
    storageBucket: 'fir-flutter-test-f5430.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvAok1JC4c8knY2YE4bg3iHm51HYGSfb0',
    appId: '1:1092688138672:ios:0330da62aff84a58764675',
    messagingSenderId: '1092688138672',
    projectId: 'fir-flutter-test-f5430',
    storageBucket: 'fir-flutter-test-f5430.appspot.com',
    iosClientId: '1092688138672-ctvhtujmsgclscvqc6bkfjumbmn1960a.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvAok1JC4c8knY2YE4bg3iHm51HYGSfb0',
    appId: '1:1092688138672:ios:0330da62aff84a58764675',
    messagingSenderId: '1092688138672',
    projectId: 'fir-flutter-test-f5430',
    storageBucket: 'fir-flutter-test-f5430.appspot.com',
    iosClientId: '1092688138672-ctvhtujmsgclscvqc6bkfjumbmn1960a.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterTest',
  );
}
