name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  dart_code_metrics: ^5.7.6
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.9
  go_router: ^14.2.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/icon/
    - assets/image/
